### ISSUE TITLE
Decide on licensing

### ISSUE THREAD

**Issue by bengl** [bengl/wishlist#3]
Should this repo have a license? Maybe not since it's a "meta" repo. I dunno. Opinions please!

**Comment by ryanseys** [comment]
Meh, throw MIT in and call it a day? No harm in adding MIT.

**Comment by bengl** [comment]
Well, because it's not code, I was thinking CC licensing. But then since all the content is in issues, there's the question of whether and how the issues are licensed.

**Comment by ryanseys** [comment]
Hmm, yea true. https://github.com/mdo/feedback and https://github.com/holman/feedback use a similar approach to a repo and don't have a license and if anyone knows anything about open source licenses it's them. With this in mind, I'd say no reason to have a license.

**Comment by bengl** [comment]
https://github.com/isaacs/github is another example.

Yeah. Sticking with no license for now and closing this issue.
